ports = {
    "ssh": {"type": "PortLiteral", "port": "22", "protocol": "6",},
    "udp/netbios-dgm": {"type": "PortLiteral", "port": "138", "protocol": "17",},
    "udp/netbios-ns": {"type": "PortLiteral", "port": "137", "protocol": "17",},
    "tcp/ssh": {"type": "PortLiteral", "port": "22", "protocol": "6",},
    "tcp": {"type": "PortLiteral", "protocol": "6",},
    "esp": {"type": "PortLiteral", "protocol": "50",},
    "ah": {"type": "PortLiteral", "protocol": "51",},
    "udp": {"type": "PortLiteral", "protocol": "17",},
    "snmp": [
        {"type": "PortLiteral", "port": "161", "protocol": "17",},
        {"type": "PortLiteral", "port": "162", "protocol": "17",},
    ],
    "udp/snmp": [
        {"type": "PortLiteral", "port": "161", "protocol": "17",},
        {"type": "PortLiteral", "port": "162", "protocol": "6",},
        {"type": "PortLiteral", "port": "162", "protocol": "17",},
    ],
    "udp/snmptrap": {"type": "PortLiteral", "port": "162", "protocol": "6",},
    "snmptrap": [
        {"type": "PortLiteral", "port": "162", "protocol": "6",},
        {"type": "PortLiteral", "port": "162", "protocol": "17",},
    ],
    "https": [
        {"type": "PortLiteral", "port": "443", "protocol": "6",},
        {"type": "PortLiteral", "port": "443", "protocol": "17",},
    ],
    "tcp/https": {"type": "PortLiteral", "port": "443", "protocol": "6",},
    "netbios-ssn": {"type": "PortLiteral", "port": "139", "protocol": "6",},
    "tcp/netbios-ssn": {"type": "PortLiteral", "port": "139", "protocol": "6",},
    "ntp": {"type": "PortLiteral", "port": "123", "protocol": "17",},
    "udp/ntp": {"type": "PortLiteral", "port": "123", "protocol": "17",},
    "tcp/tacacs": {"type": "PortLiteral", "port": "49", "protocol": "6",},
    "udp/tacacs": {"type": "PortLiteral", "port": "49", "protocol": "17",},
    "tcp/www": {"type": "PortLiteral", "port": "80", "protocol": "6",},
    "udp/www": {"type": "PortLiteral", "port": "80", "protocol": "17",},
    "tcp/http": {"type": "PortLiteral", "port": "80", "protocol": "6",},
    "ldaps": {"type": "PortLiteral", "port": "636", "protocol": "6",},
    "tcp/ldaps": {"type": "PortLiteral", "port": "636", "protocol": "6",},
    "ldap": {"type": "PortLiteral", "port": "389", "protocol": "6",},
    "tcp/ldap": {"type": "PortLiteral", "port": "389", "protocol": "6",},
    "tcp/syslog": {"type": "PortLiteral", "port": "514", "protocol": "6",},
    "udp/syslog": {"type": "PortLiteral", "port": "514", "protocol": "17",},
    "tcp/domain": {"type": "PortLiteral", "port": "53", "protocol": "6", },
    "udp/domain": {"type": "PortLiteral", "port": "53", "protocol": "17",},
    "tcp/rsh": {"type": "PortLiteral", "port": "514", "protocol": "6",},
    "icmp": {"type": "ICMPv4PortLiteral", "protocol": "1", "icmpType": "Any",},
    "any": [],
}
